version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "${DB_PORT}:5432"
    networks:
      - fly_network

  web: &web
    image: fly-dj4
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GROUPID=${GROUPID}
        - USERID=${USERID}
    volumes:
      - .:/code
    ports:
      - "${APP_PORT}:8000"
      - "${SSL_APP_PORT}:8443"
    restart: always
    env_file: .env
    depends_on:
      - db
    networks:
      - fly_network

  node:
    <<: *web
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    entrypoint: ["/entry_point_node.sh"]
    env_file: .env
    networks:
      - fly_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadmin:/root/.pgadmin
    depends_on:
      - db
    networks:
      - fly_network

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "${REDIS_PORT}:6379"
  #   volumes:
  #     - redis-data:/data
  #   networks:
  #     - fly_network

volumes:
  # mysql:
  postgres_data:
  pgadmin:
  redis-data:

networks:
  fly_network:

    # image: mysql
    # volumes:
    #   - mysql:/var/lib/mysql
    # environment:
    #   - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    #   - MYSQL_ROOT_HOST=%
    #   - MYSQL_DATABASE=${DB_DATABASE}
    #   - MYSQL_USER=${DB_USERNAME}
    #   - MYSQL_PASSWORD=${DB_PASSWORD}
    #   - MYSQL_ALLOW_EMPTY_PASSWORD=1
